export const attributesObjectsArray = [
  [
    { id: 0, item: "-", desc: "BLANK" },
    { id: 1, item: "ALD", desc: "Aldi" },
    { id: 2, item: "DNS", desc: "Dunnes" },
    { id: 3, item: "SVU", desc: "Supervalu" },
    { id: 4, item: "TSC", desc: "Tesco" },
    { id: 5, item: "LDL", desc: "Lidl" },
    { id: 6, item: "385", desc: "CS385 Superstore" }
  ],
  [
    { id: 0, item: "-", desc: "Blank" },
    { id: 0, item: "BRT", desc: "Brittle" },
    { id: 0, item: "BTY", desc: "Buttery" },
    { id: 0, item: "CBY", desc: "Crumbly" },
    { id: 0, item: "CDY", desc: "Curdy" },
    { id: 0, item: "CSE", desc: "Close Texture" },
    { id: 0, item: "DRY", desc: "Dry" },
    { id: 0, item: "FRM", desc: "Firm" },
    { id: 0, item: "FTG", desc: "Fracturing" },
    { id: 0, item: "GAS", desc: "Gas" },
    { id: 0, item: "OPN", desc: "Open" },
    { id: 0, item: "OTT", desc: "Over the top" },
    { id: 0, item: "PR", desc: "Poor" },
    { id: 0, item: "RGH", desc: "Rough" },
    { id: 0, item: "SDY", desc: "Slightly Dry" },
    { id: 0, item: "SHT", desc: "Short" },
    { id: 0, item: "SKY", desc: "Sticky" },
    { id: 0, item: "SMT", desc: "Smooth" },
    { id: 0, item: "SSY", desc: "Slightly Sticky" },
    { id: 0, item: "STR", desc: "Strand" },
    { id: 0, item: "STS", desc: "Slits" },
    { id: 0, item: "SWK", desc: "Slightly Weak" },
    { id: 0, item: "WK", desc: "Weak" }
  ],
  [
    { id: 1, item: "-", desc: "Blank" },
    { id: 1, item: "C", desc: "Medium" },
    { id: 1, item: "AGD", desc: "Agreed" },
    { id: 1, item: "BIS", desc: "Back in spec" },
    { id: 1, item: "EDR", desc: "Prioritise move" },
    { id: 1, item: "EST", desc: "Estimate" },
    { id: 1, item: "GD", desc: "Good" },
    { id: 1, item: "NE", desc: "Nice" },
    { id: 1, item: "NO", desc: "No/not" },
    { id: 1, item: "NOW", desc: "Now" },
    { id: 1, item: "OK", desc: "Open Carton / K" },
    { id: 1, item: "OOS", desc: "Out of spec" },
    { id: 1, item: "PRG", desc: "Progressive" },
    { id: 1, item: "PRO", desc: "Promotional" },
    { id: 1, item: "SAM", desc: "Samples" },
    { id: 1, item: "SEL", desc: "Sell" },
    { id: 1, item: "SH", desc: "Shape" },
    { id: 1, item: "SSH", desc: "Slightly shape" },
    { id: 1, item: "TNT", desc: "Taint" },
    { id: 1, item: "TRL", desc: "Trial Production" },
    { id: 1, item: "WAX", desc: "Wax" }
  ],
  [
    { id: 2, item: "---", desc: "Blank" },
    { id: 2, item: "AD", desc: "Acid" },
    { id: 2, item: "BAL", desc: "Balance" },
    { id: 2, item: "BLD", desc: "Bland" },
    { id: 2, item: "BTR", desc: "Bitter" },
    { id: 2, item: "CKD", desc: "Cooked" },
    { id: 2, item: "CLN", desc: "Clean" },
    { id: 2, item: "CML", desc: "Chemical" },
    { id: 2, item: "CRM", desc: "Creamy" },
    { id: 2, item: "CTS", desc: "Citrus" },
    { id: 2, item: "DTH", desc: "Depth" },
    { id: 2, item: "ESF", desc: "Early Season Fl" },
    { id: 2, item: "FMY", desc: "Farmy" },
    { id: 2, item: "FY", desc: "Fruity" },
    { id: 2, item: "GRN", desc: "Green" },
    { id: 2, item: "HGH", desc: "High" },
    { id: 2, item: "HST", desc: "High Salt" },
    { id: 2, item: "LCG", desc: "Lacking" },
    { id: 2, item: "LOW", desc: "Low" },
    { id: 2, item: "LSF", desc: "Late season fl" },
    { id: 2, item: "LST", desc: "Low salt" },
    { id: 2, item: "MLW", desc: "Mellow" },
    { id: 2, item: "NE", desc: "Nice" },
    { id: 2, item: "NTS", desc: "Notes" },
    { id: 2, item: "OAD", desc: "Over acid" },
    { id: 2, item: "OFF", desc: "Off flavour" },
    { id: 2, item: "ONN", desc: "Onion" },
    { id: 2, item: "PLN", desc: "Plain" },
    { id: 2, item: "RCD", desc: "Rancid" },
    { id: 2, item: "RD", desc: "ROI/Germany" },
    { id: 2, item: "RH", desc: "Rich" },
    { id: 2, item: "SAD", desc: "Slightly Acid" },
    { id: 2, item: "SCD", desc: "Slightly Cooked" },
    { id: 2, item: "SFY", desc: "Slightly Fruity" },
    { id: 2, item: "SHP", desc: "Sharp" },
    { id: 2, item: "SOF", desc: "Slight Off Flav" },
    { id: 2, item: "SPY", desc: "Soapy" },
    { id: 2, item: "SR", desc: "Sour" },
    { id: 2, item: "SSP", desc: "Slightly sharp" },
    { id: 2, item: "SSR", desc: "Slightly sour" },
    { id: 2, item: "STG", desc: "Strong" },
    { id: 2, item: "SVY", desc: "Savoury" },
    { id: 2, item: "SW", desc: "Slow" },
    { id: 2, item: "SWT", desc: "Sweet" },
    { id: 2, item: "VTE", desc: "Vintage" },
    { id: 2, item: "WHY", desc: "Whey" }
  ],
  [
    { id: 3, item: "-", desc: "BLANK" },
    { id: 3, item: "ALL", desc: "All (se-gg-pp)" },
    { id: 3, item: "GG", desc: "Grating" },
    { id: 3, item: "PCS", desc: "Processing" },
    { id: 3, item: "PG", desc: "Prepack and G" },
    { id: 3, item: "PPK", desc: "Prepack" },
    { id: 3, item: "SE", desc: "Slicing" },
    { id: 3, item: "4X5", desc: "4*5kg" },
    { id: 3, item: "8X2", desc: "8*2.5kg" }
  ],
  [
    { id: 4, item: "-", desc: "Blank" },
    { id: 4, item: "C", desc: "Medium" },
    { id: 4, item: "D", desc: "OUT OF SPEC FOR" },
    { id: 4, item: "E", desc: "EXTRA MATURE" },
    { id: 4, item: "H", desc: "HOLD KEEPING MA" },
    { id: 4, item: "J", desc: "HOLD SELL MILD " },
    { id: 4, item: "L", desc: "LONG KEEPING MI" },
    { id: 4, item: "M", desc: "MATURE" },
    { id: 4, item: "N", desc: "CURD" },
    { id: 4, item: "Q", desc: "QUARANTINE" },
    { id: 4, item: "S", desc: "MILD" },
    { id: 4, item: "T", desc: "FULL FLAVOUR" },
    { id: 4, item: "U", desc: "RETURN" },
    { id: 4, item: "V", desc: "VINTAGE" },
    { id: 4, item: "X", desc: "CAT1 DGRADE-GRA" },
    { id: 4, item: "Y", desc: "CAT2 DGRADE-PRO" },
    { id: 4, item: "Z", desc: "CAT3 DGRADE- PR" }
  ],
  [
    { id: 5, item: "-", desc: "Blank" },
    { id: 5, item: "BLB", desc: "Bottom Layer b" },
    { id: 5, item: "BLG", desc: "Bulging" },
    { id: 5, item: "BND", desc: "Bond" },
    { id: 5, item: "CBK", desc: "Check Bulk" },
    { id: 5, item: "DCS", desc: "Damaged carton" },
    { id: 5, item: "DST", desc: "Dusty" },
    { id: 5, item: "FWT", desc: "Fixed Weights" },
    { id: 5, item: "GSH", desc: "Good Shapes" },
    { id: 5, item: "IPT", desc: "Incorrect Pallet" },
    { id: 5, item: "MHT", desc: "Move to high temp" },
    { id: 5, item: "MLT", desc: "Move to low temp" },
    { id: 5, item: "MNT", desc: "Move to norm temp" },
    { id: 5, item: "MPT", desc: "Mixed Pallets" },
    { id: 5, item: "MUK", desc: "Move UK" },
    { id: 5, item: "NIL", desc: "Nil Stock" },
    { id: 5, item: "NOS", desc: "No Sample" },
    { id: 5, item: "PSH", desc: "Poor Shapes" },
    { id: 5, item: "RBG", desc: "Rebag" },
    { id: 5, item: "RTN", desc: "Return" }
  ],
  [
    { id: 6, item: "-", desc: "BLANK" },
    { id: 6, item: "ADJ", desc: "Adjuncts" },
    { id: 6, item: "BK", desc: "Black" },
    { id: 6, item: "BWN", desc: "Blown" },
    { id: 6, item: "CCD", desc: "Cold Curd" },
    { id: 6, item: "CRS", desc: "Crystals" },
    { id: 6, item: "ENZ", desc: "Enzyme" },
    { id: 6, item: "FFL", desc: "Tasty/Full Flavour" },
    { id: 6, item: "FNL", desc: "Functional" },
    { id: 6, item: "GBE", desc: "Good Balance" },
    { id: 6, item: "GBY", desc: "Good Body" },
    { id: 6, item: "GRN", desc: "Green" },
    { id: 6, item: "GSP", desc: "Green Spot" },
    { id: 6, item: "HIC", desc: "High colour" },
    { id: 6, item: "HME", desc: "Histamine" },
    { id: 6, item: "LAC", desc: "Lacking" },
    { id: 6, item: "MLD", desc: "Mould" },
    { id: 6, item: "MTD", desc: "Mottled" },
    { id: 6, item: "PBC", desc: "Probiotic" },
    { id: 6, item: "PCS", desc: "Processing" },
    { id: 6, item: "PK", desc: "Peaked" },
    { id: 6, item: "PKG", desc: "Peaking" },
    { id: 6, item: "PLE", desc: "Pale" },
    { id: 6, item: "PNG", desc: "Pinking" },
    { id: 6, item: "PNK", desc: "Pink" },
    { id: 6, item: "PSH", desc: "Poor Shapes" },
    { id: 6, item: "RED", desc: "Red" },
    { id: 6, item: "SKG", desc: "Slightly Peaking" },
    { id: 6, item: "SPS", desc: "Black Specs" },
    { id: 6, item: "SS", desc: "In skins" },
    { id: 6, item: "SSD", desc: "Show Standard" },
    { id: 6, item: "STG", desc: "Strong" },
    { id: 6, item: "STY", desc: "Steady" },
    { id: 6, item: "TEX", desc: "Texture" },
    { id: 6, item: "VAR", desc: "Variable" },
    { id: 6, item: "WTE", desc: "White" },
    { id: 6, item: "YLW", desc: "Yellow" }
  ],
  [
    { id: 7, item: "-", desc: "Blank" },
    { id: 7, item: "ANI", desc: "Animal" },
    { id: 7, item: "PLT", desc: "Plant" },
    { id: 7, item: "VGA", desc: "Vegan" }
  ],
  [
    { id: 8, item: "Select a country...", desc: "" },
    { id: 8, item: "USA", desc: "United States of America" },
    { id: 8, item: "GBR", desc: "United Kingdom" },
    { id: 8, item: "FRA", desc: "France" },
    { id: 8, item: "ESP", desc: "Spain" },
    { id: 8, item: "BEL", desc: "Belgium" },
    { id: 8, item: "AFG", desc: "Afghanistan" },
    { id: 8, item: "ALB", desc: "Albania" },
    { id: 8, item: "DZA", desc: "Algeria" },
    { id: 8, item: "ASM", desc: "American Samoa" },
    { id: 8, item: "AND", desc: "Andorra" },
    { id: 8, item: "AGO", desc: "Angola" },
    { id: 8, item: "AIA", desc: "Anguilla" },
    { id: 8, item: "ATA", desc: "Antarctica" },
    { id: 8, item: "ATG", desc: "Antigua and Barbuda" },
    { id: 8, item: "ARG", desc: "Argentina" },
    { id: 8, item: "ARM", desc: "Armenia" },
    { id: 8, item: "ABW", desc: "Aruba" },
    { id: 8, item: "AUS", desc: "Australia" },
    { id: 8, item: "AUT", desc: "Austria" },
    { id: 8, item: "AZE", desc: "Azerbaijan" },
    { id: 8, item: "BHS", desc: "Bahamas (the)" },
    { id: 8, item: "BHR", desc: "Bahrain" },
    { id: 8, item: "BGD", desc: "Bangladesh" },
    { id: 8, item: "BRB", desc: "Barbados" },
    { id: 8, item: "BLR", desc: "Belarus" },

    { id: 8, item: "BLZ", desc: "Belize" },
    { id: 8, item: "BEN", desc: "Benin" },
    { id: 8, item: "BMU", desc: "Bermuda" },
    { id: 8, item: "BTN", desc: "Bhutan" },
    { id: 8, item: "BOL", desc: "Bolivia (Plurinational State of)" },
    { id: 8, item: "BES", desc: "Bonaire, Sint Eustatius and Saba" },
    { id: 8, item: "BIH", desc: "Bosnia and Herzegovina" },
    { id: 8, item: "BWA", desc: "Botswana" },
    { id: 8, item: "BVT", desc: "Bouvet Island" },
    { id: 8, item: "BRA", desc: "Brazil" },
    { id: 8, item: "IOT", desc: "British Indian Ocean Territory (the)" },
    { id: 8, item: "BRN", desc: "Brunei Darussalam" },
    { id: 8, item: "BGR", desc: "Bulgaria" },
    { id: 8, item: "BFA", desc: "Burkina Faso" },
    { id: 8, item: "BDI", desc: "Burundi" },
    { id: 8, item: "CPV", desc: "Cabo Verde" },
    { id: 8, item: "KHM", desc: "Cambodia" },
    { id: 8, item: "CMR", desc: "Cameroon" },
    { id: 8, item: "CAN", desc: "Canada" },
    { id: 8, item: "CYM", desc: "Cayman Islands (the)" },
    { id: 8, item: "CAF", desc: "Central African Republic (the)" },
    { id: 8, item: "TCD", desc: "Chad" },
    { id: 8, item: "CHL", desc: "Chile" },
    { id: 8, item: "CHN", desc: "China" },
    { id: 8, item: "CXR", desc: "Christmas Island" },
    { id: 8, item: "CCK", desc: "Cocos (Keeling) Islands (the)" },
    { id: 8, item: "COL", desc: "Colombia" },
    { id: 8, item: "COM", desc: "Comoros (the)" },
    { id: 8, item: "COD", desc: "Congo (the Democratic Republic of the)" },
    { id: 8, item: "COG", desc: "Congo (the)" },
    { id: 8, item: "COK", desc: "Cook Islands (the)" },
    { id: 8, item: "CRI", desc: "Costa Rica" },
    { id: 8, item: "HRV", desc: "Croatia" },
    { id: 8, item: "CUB", desc: "Cuba" },
    { id: 8, item: "CUW", desc: "Curaçao" },
    { id: 8, item: "CYP", desc: "Cyprus" },
    { id: 8, item: "CZE", desc: "Czechia" },
    { id: 8, item: "CIV", desc: "Côte d'Ivoire" },
    { id: 8, item: "DNK", desc: "Denmark" },
    { id: 8, item: "DJI", desc: "Djibouti" },
    { id: 8, item: "DMA", desc: "Dominica" },
    { id: 8, item: "DOM", desc: "Dominican Republic (the)" },
    { id: 8, item: "ECU", desc: "Ecuador" },
    { id: 8, item: "EGY", desc: "Egypt" },
    { id: 8, item: "SLV", desc: "El Salvador" },
    { id: 8, item: "GNQ", desc: "Equatorial Guinea" },
    { id: 8, item: "ERI", desc: "Eritrea" },
    { id: 8, item: "EST", desc: "Estonia" },
    { id: 8, item: "SWZ", desc: "Eswatini" },
    { id: 8, item: "ETH", desc: "Ethiopia" },
    { id: 8, item: "FLK", desc: "Falkland Islands (the) [Malvinas]" },
    { id: 8, item: "FRO", desc: "Faroe Islands (the)" },
    { id: 8, item: "FJI", desc: "Fiji" },
    { id: 8, item: "FIN", desc: "Finland" },
    { id: 8, item: "GUF", desc: "French Guiana" },
    { id: 8, item: "PYF", desc: "French Polynesia" },
    { id: 8, item: "ATF", desc: "French Southern Territories (the)" },
    { id: 8, item: "GAB", desc: "Gabon" },
    { id: 8, item: "GMB", desc: "Gambia (the)" },
    { id: 8, item: "GEO", desc: "Georgia" },
    { id: 8, item: "DEU", desc: "Germany" },
    { id: 8, item: "GHA", desc: "Ghana" },
    { id: 8, item: "GIB", desc: "Gibraltar" },
    { id: 8, item: "GRC", desc: "Greece" },
    { id: 8, item: "GRL", desc: "Greenland" },
    { id: 8, item: "GRD", desc: "Grenada" },
    { id: 8, item: "GLP", desc: "Guadeloupe" },
    { id: 8, item: "GUM", desc: "Guam" },
    { id: 8, item: "GTM", desc: "Guatemala" },
    { id: 8, item: "GGY", desc: "Guernsey" },
    { id: 8, item: "GIN", desc: "Guinea" },
    { id: 8, item: "GNB", desc: "Guinea-Bissau" },
    { id: 8, item: "GUY", desc: "Guyana" },
    { id: 8, item: "HTI", desc: "Haiti" },
    { id: 8, item: "HMD", desc: "Heard Island and McDonald Islands" },
    { id: 8, item: "VAT", desc: "Holy See (the)" },
    { id: 8, item: "HND", desc: "Honduras" },
    { id: 8, item: "HKG", desc: "Hong Kong" },
    { id: 8, item: "HUN", desc: "Hungary" },
    { id: 8, item: "ISL", desc: "Iceland" },
    { id: 8, item: "IND", desc: "India" },
    { id: 8, item: "IDN", desc: "Indonesia" },
    { id: 8, item: "IRN", desc: "Iran (Islamic Republic of)" },
    { id: 8, item: "IRQ", desc: "Iraq" },
    { id: 8, item: "IRL", desc: "Ireland" },
    { id: 8, item: "IMN", desc: "Isle of Man" },
    { id: 8, item: "ISR", desc: "Israel" },
    { id: 8, item: "ITA", desc: "Italy" },
    { id: 8, item: "JAM", desc: "Jamaica" },
    { id: 8, item: "JPN", desc: "Japan" },
    { id: 8, item: "JEY", desc: "Jersey" },
    { id: 8, item: "JOR", desc: "Jordan" },
    { id: 8, item: "KAZ", desc: "Kazakhstan" },
    { id: 8, item: "KEN", desc: "Kenya" },
    { id: 8, item: "KIR", desc: "Kiribati" },
    { id: 8, item: "PRK", desc: "Korea (the Democratic People's Republic of)" },
    { id: 8, item: "KOR", desc: "Korea (the Republic of)" },
    { id: 8, item: "KWT", desc: "Kuwait" },
    { id: 8, item: "KGZ", desc: "Kyrgyzstan" },
    { id: 8, item: "LAO", desc: "Lao People's Democratic Republic (the)" },
    { id: 8, item: "LVA", desc: "Latvia" },
    { id: 8, item: "LBN", desc: "Lebanon" },
    { id: 8, item: "LSO", desc: "Lesotho" },
    { id: 8, item: "LBR", desc: "Liberia" },
    { id: 8, item: "LBY", desc: "Libya" },
    { id: 8, item: "LIE", desc: "Liechtenstein" },
    { id: 8, item: "LTU", desc: "Lithuania" },
    { id: 8, item: "LUX", desc: "Luxembourg" },
    { id: 8, item: "MAC", desc: "Macao" },
    { id: 8, item: "MDG", desc: "Madagascar" },
    { id: 8, item: "MWI", desc: "Malawi" },
    { id: 8, item: "MYS", desc: "Malaysia" },
    { id: 8, item: "MDV", desc: "Maldives" },
    { id: 8, item: "MLI", desc: "Mali" },
    { id: 8, item: "MLT", desc: "Malta" },
    { id: 8, item: "MHL", desc: "Marshall Islands (the)" },
    { id: 8, item: "MTQ", desc: "Martinique" },
    { id: 8, item: "MRT", desc: "Mauritania" },
    { id: 8, item: "MUS", desc: "Mauritius" },
    { id: 8, item: "MYT", desc: "Mayotte" },
    { id: 8, item: "MEX", desc: "Mexico" },
    { id: 8, item: "FSM", desc: "Micronesia (Federated States of)" },
    { id: 8, item: "MDA", desc: "Moldova (the Republic of)" },
    { id: 8, item: "MCO", desc: "Monaco" },
    { id: 8, item: "MNG", desc: "Mongolia" },
    { id: 8, item: "MNE", desc: "Montenegro" },
    { id: 8, item: "MSR", desc: "Montserrat" },
    { id: 8, item: "MAR", desc: "Morocco" },
    { id: 8, item: "MOZ", desc: "Mozambique" },
    { id: 8, item: "MMR", desc: "Myanmar" },
    { id: 8, item: "NAM", desc: "Namibia" },
    { id: 8, item: "NRU", desc: "Nauru" },
    { id: 8, item: "NPL", desc: "Nepal" },
    { id: 8, item: "NLD", desc: "Netherlands (the)" },
    { id: 8, item: "NCL", desc: "New Caledonia" },
    { id: 8, item: "NZL", desc: "New Zealand" },
    { id: 8, item: "NIC", desc: "Nicaragua" },
    { id: 8, item: "NER", desc: "Niger (the)" },
    { id: 8, item: "NGA", desc: "Nigeria" },
    { id: 8, item: "NIU", desc: "Niue" },
    { id: 8, item: "NFK", desc: "Norfolk Island" },
    { id: 8, item: "MNP", desc: "Northern Mariana Islands (the)" },
    { id: 8, item: "NOR", desc: "Norway" },
    { id: 8, item: "OMN", desc: "Oman" },
    { id: 8, item: "PAK", desc: "Pakistan" },
    { id: 8, item: "PLW", desc: "Palau" },
    { id: 8, item: "PSE", desc: "Palestine, State of" },
    { id: 8, item: "PAN", desc: "Panama" },
    { id: 8, item: "PNG", desc: "Papua New Guinea" },
    { id: 8, item: "PRY", desc: "Paraguay" },
    { id: 8, item: "PER", desc: "Peru" },
    { id: 8, item: "PHL", desc: "Philippines (the)" },
    { id: 8, item: "PCN", desc: "Pitcairn" },
    { id: 8, item: "POL", desc: "Poland" },
    { id: 8, item: "PRT", desc: "Portugal" },
    { id: 8, item: "PRI", desc: "Puerto Rico" },
    { id: 8, item: "QAT", desc: "Qatar" },
    { id: 8, item: "MKD", desc: "Republic of North Macedonia" },
    { id: 8, item: "ROU", desc: "Romania" },
    { id: 8, item: "RUS", desc: "Russian Federation (the)" },
    { id: 8, item: "RWA", desc: "Rwanda" },
    { id: 8, item: "REU", desc: "Réunion" },
    { id: 8, item: "BLM", desc: "Saint Barthélemy" },
    {
      id: 8,
      item: "SHN",
      desc: "Saint Helena, Ascension and Tristan da Cunha"
    },
    { id: 8, item: "KNA", desc: "Saint Kitts and Nevis" },
    { id: 8, item: "LCA", desc: "Saint Lucia" },
    { id: 8, item: "MAF", desc: "Saint Martin (French part)" },
    { id: 8, item: "SPM", desc: "Saint Pierre and Miquelon" },
    { id: 8, item: "VCT", desc: "Saint Vincent and the Grenadines" },
    { id: 8, item: "WSM", desc: "Samoa" },
    { id: 8, item: "SMR", desc: "San Marino" },
    { id: 8, item: "STP", desc: "Sao Tome and Principe" },
    { id: 8, item: "SAU", desc: "Saudi Arabia" },
    { id: 8, item: "SEN", desc: "Senegal" },
    { id: 8, item: "SRB", desc: "Serbia" },
    { id: 8, item: "SYC", desc: "Seychelles" },
    { id: 8, item: "SLE", desc: "Sierra Leone" },
    { id: 8, item: "SGP", desc: "Singapore" },
    { id: 8, item: "SXM", desc: "Sint Maarten (Dutch part)" },
    { id: 8, item: "SVK", desc: "Slovakia" },
    { id: 8, item: "SVN", desc: "Slovenia" },
    { id: 8, item: "SLB", desc: "Solomon Islands" },
    { id: 8, item: "SOM", desc: "Somalia" },
    { id: 8, item: "ZAF", desc: "South Africa" },
    {
      id: 8,
      item: "SGS",
      desc: "South Georgia and the South Sandwich Islands"
    },
    { id: 8, item: "SSD", desc: "South Sudan" },

    { id: 8, item: "LKA", desc: "Sri Lanka" },
    { id: 8, item: "SDN", desc: "Sudan (the)" },
    { id: 8, item: "SUR", desc: "Suriname" },
    { id: 8, item: "SJM", desc: "Svalbard and Jan Mayen" },
    { id: 8, item: "SWE", desc: "Sweden" },
    { id: 8, item: "CHE", desc: "Switzerland" },
    { id: 8, item: "SYR", desc: "Syrian Arab Republic" },
    { id: 8, item: "TWN", desc: "Taiwan" },
    { id: 8, item: "TJK", desc: "Tajikistan" },
    { id: 8, item: "TZA", desc: "Tanzania" },
    { id: 8, item: "THA", desc: "Thailand" },
    { id: 8, item: "TLS", desc: "Timor-Leste" },
    { id: 8, item: "TGO", desc: "Togo" },
    { id: 8, item: "TKL", desc: "Tokelau" },
    { id: 8, item: "TON", desc: "Tonga" },
    { id: 8, item: "TTO", desc: "Trinidad and Tobago" },
    { id: 8, item: "TUN", desc: "Tunisia" },
    { id: 8, item: "TUR", desc: "Turkey" },
    { id: 8, item: "TKM", desc: "Turkmenistan" },
    { id: 8, item: "TCA", desc: "Turks and Caicos Islands (the)" },
    { id: 8, item: "TUV", desc: "Tuvalu" },
    { id: 8, item: "UGA", desc: "Uganda" },
    { id: 8, item: "UKR", desc: "Ukraine" },
    { id: 8, item: "ARE", desc: "United Arab Emirates (the)" },
    { id: 8, item: "UMI", desc: "US Minor Outlying Islands" },
    { id: 8, item: "URY", desc: "Uruguay" },
    { id: 8, item: "UZB", desc: "Uzbekistan" },
    { id: 8, item: "VUT", desc: "Vanuatu" },
    { id: 8, item: "VEN", desc: "Venezuela (Bolivarian Republic of)" },
    { id: 8, item: "VNM", desc: "Viet Nam" },
    { id: 8, item: "VGB", desc: "Virgin Islands" },
    { id: 8, item: "VIR", desc: "Virgin Islands (U.S.)" },
    { id: 8, item: "WLF", desc: "Wallis and Futuna" },
    { id: 8, item: "ESH", desc: "Western Sahara" },
    { id: 8, item: "YEM", desc: "Yemen" },
    { id: 8, item: "ZMB", desc: "Zambia" },
    { id: 8, item: "ZWE", desc: "Zimbabwe" },
    { id: 8, item: "ALA", desc: "Åland Islands" }
  ]
];
